src/Entity/MatierePremiere.php
<?php

namespace App\Entity;

use App\Repository\MatierePremiereRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MatierePremiereRepository::class)
 */
class MatierePremiere
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $unite_mesure;

    /**
     * @ORM\Column(type="integer")
     */
    private $seuil_alerte;

    /**
     * @ORM\Column(type="integer")
     */
    private $seuil_critique;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_ht;

    /**
     * @ORM\OneToMany(targetEntity=StockMP::class, mappedBy="matiere_premiere", orphanRemoval=true, cascade={"persist"})
     */
    private $actionStock;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Fournisseur::class, inversedBy="matierePremieres", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $fournisseur;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $stock_sobele;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $stock_marjoris;

    public function __construct()
    {
        $this->actionStock = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getUniteMesure(): ?string
    {
        return $this->unite_mesure;
    }

    public function setUniteMesure(string $unite_mesure): self
    {
        $this->unite_mesure = $unite_mesure;

        return $this;
    }

    public function getSeuilAlerte(): ?int
    {
        return $this->seuil_alerte;
    }

    public function setSeuilAlerte(int $seuil_alerte): self
    {
        $this->seuil_alerte = $seuil_alerte;

        return $this;
    }

    public function getSeuilCritique(): ?int
    {
        return $this->seuil_critique;
    }

    public function setSeuilCritique(int $seuil_critique): self
    {
        $this->seuil_critique = $seuil_critique;

        return $this;
    }

    public function getPrixHt(): ?float
    {
        return $this->prix_ht;
    }

    public function setPrixHt(float $prix_ht): self
    {
        $this->prix_ht = $prix_ht;

        return $this;
    }

    public function __toString(): string
    {
        return $this->ref;
    }

    /**
     * @return Collection|StockMP[]
     */
    public function getActionStock(): Collection
    {
        return $this->actionStock;
    }

    public function addActionStock(StockMP $actionStock): self
    {
        if (!$this->actionStock->contains($actionStock)) {
            $this->actionStock[] = $actionStock;
            $actionStock->setMatierePremiere($this);
        }

        return $this;
    }

    public function removeActionStock(StockMP $actionStock): self
    {
        if ($this->actionStock->removeElement($actionStock)) {
            // set the owning side to null (unless already changed)
            if ($actionStock->getMatierePremiere() === $this) {
                $actionStock->setMatierePremiere(null);
            }
        }

        return $this;
    }


    public function getEtat(): string
    {
        if ($this->stock_marjoris < $this->stock_sobele) $stockMin = $this->stock_marjoris;
        else $stockMin = $this->stock_sobele;

        if ($stockMin <= $this->seuil_critique) return 'danger';
        elseif ($this->$stockMin <= $this->seuil_alerte) return 'warning';
        else return 'success';
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?Fournisseur $fournisseur): self
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

    public function getStockSobele(): ?float
    {
        return $this->stock_sobele;
    }

    public function setStockSobele(float $stock_sobele): self
    {
        $this->stock_sobele = $stock_sobele;

        return $this;
    }

    public function getStockMarjoris(): ?float
    {
        return $this->stock_marjoris;
    }

    public function setStockMarjoris(float $stock_marjoris): self
    {
        $this->stock_marjoris = $stock_marjoris;

        return $this;
    }

    public function opStockSobele(float $op): self
    {
        $this->stock_sobele += $op;
        return $this;
    }

    public function opStockMarjoris(float $op): self
    {
        $this->stock_marjoris += $op;
        return $this;
    }
}

src/Form/MatierePremiereType.php
<?php

namespace App\Form;

use App\Entity\MatierePremiere;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MatierePremiereType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ref')
            ->add('unite_mesure', ChoiceType::class, [
                'label' => 'Vente',
                'choices' => [
                    'à l\'unité' => 'UNITE',
                    'au mètre' => 'METRE',
                ]
            ])
            /*->add('stock')*/
            ->add('seuil_alerte')
            ->add('seuil_critique')
            ->add('prix_ht', MoneyType::class)
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'fourniture' => 'fourniture',
                    'tissu' => 'tissu',
                    'noeud' => 'noeud'
                ]
            ])
            ->add('fournisseur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MatierePremiere::class,
        ]);
    }
}

src/Controller/MatierePremiereController.php
<?php

namespace App\Controller;

use App\Entity\MatierePremiere;
use App\Entity\StockMP;
use App\Form\MatierePremiereType;
use App\Form\StockMPType;
use App\Repository\MatierePremiereRepository;
use App\Repository\StockMPRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/matiere_premiere")
 */
class MatierePremiereController extends AbstractController
{
    /**
     * @Route("/", name="matiere_premiere_index", methods={"GET"})
     */
    public function index(MatierePremiereRepository $repository): Response
    {
        return $this->render('matiere_premiere/index.html.twig', [
            'matiere_premieres' => $repository->findBy([],['type' => 'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="matiere_premiere_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $matierePremiere = new MatierePremiere();
        $matierePremiere
            ->setStockMarjoris(0)
            ->setStockSobele(0)
            ->setSeuilAlerte(20)
            ->setSeuilCritique(10);
        $form = $this->createForm(MatierePremiereType::class, $matierePremiere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($matierePremiere);
            $entityManager->flush();

            return $this->redirectToRoute('matiere_premiere_index');
        }

        return $this->render('matiere_premiere/new.html.twig', [
            'matiere_premiere' => $matierePremiere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="matiere_premiere_show", methods={"GET"})
     */
    public function show(MatierePremiere $matierePremiere): Response
    {
        return $this->render('matiere_premiere/show.html.twig', [
            'matiere_premiere' => $matierePremiere,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="matiere_premiere_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, MatierePremiere $matierePremiere): Response
    {
        $form = $this->createForm(MatierePremiereType::class, $matierePremiere);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('matiere_premiere_index');
        }

        return $this->render('matiere_premiere/edit.html.twig', [
            'matiere_premiere' => $matierePremiere,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="matiere_premiere_delete", methods={"DELETE"})
     */
    public function delete(Request $request, MatierePremiere $matierePremiere): Response
    {
        if ($this->isCsrfTokenValid('delete'.$matierePremiere->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($matierePremiere);
            $entityManager->flush();
        }

        return $this->redirectToRoute('matiere_premiere_index');
    }

    /**
     * @Route("/{id}/stock", name="matiere_premiere_stock_index", methods={"GET"})
     */
    public function stock(StockMPRepository $repository, MatierePremiere $matierePremiere): Response
    {
        return $this->render('stock_mp/index.html.twig', [
            'stock_mps_1' => $repository->findBy(['matiere_premiere' => $matierePremiere, 'lieu' => 'SOBELE'],['date' => 'DESC']),
            'stock_mps_2' => $repository->findBy(['matiere_premiere' => $matierePremiere, 'lieu' => 'MARJORIS'],['date' => 'DESC']),
            'matiere_premiere' => $matierePremiere,
        ]);
    }

    /**
     * @Route("/{id}/stock/update/{lieu}", name="matiere_premiere_stock_update", methods={"GET","POST"})
     */
    public function updateStock(Request $request, MatierePremiere $matierePremiere, $lieu): Response
    {
        $stockMP = new StockMP();
        $stockMP
            ->setLieu($lieu)
            ->setDate(new \DateTime())
            ->setMatierePremiere($matierePremiere)
            ->setOrigine("Modification manuelle");
        $form = $this->createForm(StockMPType::class, $stockMP);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $stockMP->appli();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($matierePremiere);
            $entityManager->flush();

            return $this->redirectToRoute('matiere_premiere_stock_index', ['id' => $matierePremiere->getId()]);
        }

        switch ($lieu) {
            case 'MARJORIS':
                $oldStock = $matierePremiere->getStockMarjoris();
                break;
            case 'SOBELE':
                $oldStock = $matierePremiere->getStockSobele();
                break;
        }

        return $this->render('stock_mp/new.html.twig', [
            'stock_mp' => $stockMP,
            'matiere_premiere' => $matierePremiere,
            'form' => $form->createView(),
            'oldStock' => $oldStock,
        ]);
    }

    /**
     * @Route("{idProduit}/stock/{id}", name="matiere_premiere_stock_delete", methods={"DELETE"})
     */
    public function deleteStock(Request $request, MatierePremiere $matierePremiere, StockMP $stockMP): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stockMP->getId(), $request->request->get('_token'))) {
            // TODO: Géréer l'annulation d'une action du stock

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stockMP);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_stock_index');
    }

}

templates/matiere_premiere/_delete_form.html.twig
<form method="post" action="{{ path('matiere_premiere_delete', {'id': matiere_premiere.id}) }}" onsubmit="return confirm('Etes vous sur de vouloir supprimer cette matière première');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ matiere_premiere.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/matiere_premiere/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
<div class="row mb-3">
    <div class="col">{{ form_row(form.ref, {'label': 'Référence *'}) }}</div>
    <div class="col">{{ form_row(form.type) }}</div>
    <div class="col">{{ form_row(form.fournisseur) }}</div>
</div>
<div class="row mb-3">
    <div class="col">{{ form_row(form.seuil_alerte , {'label': 'Seuil alerte *'}) }}</div>
    <div class="col">{{ form_row(form.seuil_critique, {'label': 'Seuil critique *'}) }}</div>
    <div class="col">{{ form_row(form.prix_ht, {'label': 'Prix ht *'}) }}</div>
    <div class="col">{{ form_row(form.unite_mesure) }}</div>
</div>
<div>
    <button class="btn btn-primary">Enregistrer</button>
    <a href="{{ path('matiere_premiere_index') }}" class="btn btn-secondary">Retour</a>
</div>
{{ form_end(form) }}

templates/matiere_premiere/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Matière première - {{ matiere_premiere.ref }}
{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between">
        <h1 class="mb-5">Modifier Matière première : {{ matiere_premiere.ref }}</h1>
    </div>

    {{ include('matiere_premiere/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/articles/tagsinput/bootstrap-tagsinput.js') }}"></script>
    <script src="{{ asset('js/articles/typehead.js') }}"></script>
    <script src="{{ asset('js/articles/main.js') }}"></script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/tagsinput.css') }}">
{% endblock %}

templates/matiere_premiere/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Matières Premieres{% endblock %}

{% block body %}
    <h1>Matières Premières</h1>


    <table class="table">
        <thead>
            <tr>
                <th>Référence</th>
                <th>Unite de mesure</th>
                <th>Stock SOBELE | MARJORIS</th>
                <th>Prix ht</th>
                <th scope="col" class="text-end">
                <a href="{{ path('matiere_premiere_new') }}" class="btn btn-success">Ajouter une MP</a>
                </th>
            </tr>
        </thead>
        <tbody>
        {% for matiere_premiere in matiere_premieres %}

                <tr class="align-middle{# table-{{ matiere_premiere.etat }}#}">
                    <td>{{ matiere_premiere.ref }}</td>
                    <td>{{ matiere_premiere.uniteMesure }}</td>
                    <td>
                        <a href="{{ path('matiere_premiere_stock_index', {id: matiere_premiere.id}) }}" class="bi bi-arrow-down-up"></a>
                        {{ matiere_premiere.stockSobele }} | {{ matiere_premiere.stockMarjoris }}
                    </td>
                    <td>{{ matiere_premiere.prixHt }}</td>
                    <td class="text-end">
                        <a href="{{ path('matiere_premiere_edit', {'id': matiere_premiere.id}) }}" class="btn btn-primary">Modifier</a>
                    </td>
                </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucune matière première</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/matiere_premiere/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle matière première{% endblock %}

{% block body %}
    <h1 class="mb-5">Nouvelle matière première</h1>

    {{ include('matiere_premiere/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/articles/tagsinput/bootstrap-tagsinput.js') }}"></script>
    <script src="{{ asset('js/articles/typehead.js') }}"></script>
    <script src="{{ asset('js/articles/main.js') }}"></script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/tagsinput.css') }}">
{% endblock %}

templates/matiere_premiere/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matières Premières{% endblock %}

{% block body %}
    <h1>Matière Premières</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ matiere_premiere.id }}</td>
            </tr>
            <tr>
                <th>Référence</th>
                <td>{{ matiere_premiere.ref }}</td>
            </tr>
            <tr>
                <th>Unite de mesure</th>
                <td>{{ matiere_premiere.uniteMesure }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ matiere_premiere.stock }}</td>
            </tr>
            <tr>
                <th>Seuil d'alerte</th>
                <td>{{ matiere_premiere.seuilAlerte }}</td>
            </tr>
            <tr>
                <th>Seuil critique</th>
                <td>{{ matiere_premiere.seuilCritique }}</td>
            </tr>
            <tr>
                <th>Prix ht</th>
                <td>{{ matiere_premiere.prixHt }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('matiere_premiere_index') }}">Retourner à la liste</a>

    <a href="{{ path('matiere_premiere_edit', {'id': matiere_premiere.id}) }}">Modifier</a>

{% endblock %}