src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    /**
     * @ORM\ManyToOne(targetEntity=CollectionArticle::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $collection;

    /**
     * @ORM\ManyToOne(targetEntity=Taille::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * @var Taille
     */
    private $taille;

    /**
     * @ORM\Column(type="integer")
     */
    private $seuil_alerte;

    /**
     * @ORM\Column(type="integer")
     */
    private $seuil_critique;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_public;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_revendeur;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\Column(type="boolean")
     */
    private $dans_catalogue;

    /**
     * @ORM\OneToMany(targetEntity=StockProduit::class, mappedBy="produit", orphanRemoval=true, cascade={"persist"})
     */
    private $actionStock;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $refCompta;

    public function getEtat(): string {
        if ($this->dans_catalogue) {
            if ($this->stock <= $this->seuil_critique) return 'danger';
            elseif ($this->stock <= $this->seuil_alerte) return 'warning';
            else return 'success';
        } else return 'secondary';
    }

    public function __construct()
    {
        $this->stock = 0;
        $this->actionStock = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getCollection(): ?CollectionArticle
    {
        return $this->collection;
    }

    public function setCollection(?CollectionArticle $collection): self
    {
        $this->collection = $collection;

        return $this;
    }

    public function getTaille(): ?Taille
    {
        return $this->taille;
    }

    public function setTaille(?Taille $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getStock(): int
    {
        return $this->stock;
    }

    public function opStock(int $op): self
    {
        $this->stock += $op;
        return $this;
    }

    public function getSeuilAlerte(): ?int
    {
        return $this->seuil_alerte;
    }

    public function setSeuilAlerte(int $seuil_alerte): self
    {
        $this->seuil_alerte = $seuil_alerte;

        return $this;
    }

    public function getSeuilCritique(): ?int
    {
        return $this->seuil_critique;
    }

    public function setSeuilCritique(int $seuil_critique): self
    {
        $this->seuil_critique = $seuil_critique;

        return $this;
    }

    public function getPrixPublic(): ?float
    {
        return $this->prix_public;
    }

    public function setPrixPublic(float $prix_public): self
    {
        $this->prix_public = $prix_public;

        return $this;
    }

    public function getPrixRevendeur(): ?float
    {
        return $this->prix_revendeur;
    }

    public function setPrixRevendeur(float $prix_revendeur): self
    {
        $this->prix_revendeur = $prix_revendeur;

        return $this;
    }

    public function getDansCatalogue(): ?bool
    {
        return $this->dans_catalogue;
    }

    public function setDansCatalogue(bool $dans_catalogue): self
    {
        $this->dans_catalogue = $dans_catalogue;

        return $this;
    }

    /**
     * @return Collection|StockProduit[]
     */
    public function getActionStock(): Collection
    {
        return $this->actionStock;
    }

    public function addActionStock(StockProduit $actionStock): self
    {
        if (!$this->actionStock->contains($actionStock)) {
            $this->actionStock[] = $actionStock;
            $actionStock->setProduit($this);
        }

        return $this;
    }

    public function removeActionStock(StockProduit $actionStock): self
    {
        if ($this->actionStock->removeElement($actionStock)) {
            // set the owning side to null (unless already changed)
            if ($actionStock->getProduit() === $this) {
                $actionStock->setProduit(null);
            }
        }

        return $this;
    }

    public function __toString(): string {
        return $this->ref;
    }

    public function getArticle(): Article {
        return $this->taille->getArticle();
    }

    public function getRefCompta(): ?string
    {
        return $this->refCompta;
    }

    public function setRefCompta(?string $refCompta): self
    {
        $this->refCompta = $refCompta;

        return $this;
    }

}

src/Entity/Taille.php
<?php

namespace App\Entity;

use App\Repository\TailleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TailleRepository::class)
 */
class Taille
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="tailles", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    /**
     * @ORM\OneToMany(targetEntity=UtiliseMP::class, mappedBy="taille", orphanRemoval=true, cascade={"persist"})
     */
    private $utiliseMPs;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $quantite_tissu;

    public function __construct()
    {
        $this->utiliseMPs = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function __toString() {
        return $this->nom;
    }

    /**
     * @return Collection|UtiliseMP[]
     */
    public function getUtiliseMPs(): Collection
    {
        return $this->utiliseMPs;
    }

    public function addUtiliseMP(UtiliseMP $utiliseMP): self
    {
        if (!$this->utiliseMPs->contains($utiliseMP)) {
            $this->utiliseMPs[] = $utiliseMP;
            $utiliseMP->setTaille($this);
        }

        return $this;
    }

    public function removeUtiliseMP(UtiliseMP $utiliseMP): self
    {
        if ($this->utiliseMPs->removeElement($utiliseMP)) {
            // set the owning side to null (unless already changed)
            if ($utiliseMP->getTaille() === $this) {
                $utiliseMP->setTaille(null);
            }
        }

        return $this;
    }


    /**
     * Return false if MPs is not defined else return true
     * @return bool
     */
    public function getMpDef(): bool {
        if ($this->utiliseMPs[0] == null) return false;
        else return true;
    }

    public function getQuantiteTissu(): ?float
    {
        return $this->quantite_tissu;
    }

    public function setQuantiteTissu(float $quantite_tissu): self
    {
        $this->quantite_tissu = $quantite_tissu;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $mb = ['attr' => ['class' => 'mb-3']];
        $builder
            ->add('ref', null, $mb)
            ->add('refCompta', TextType::class, [
                'attr' => ['class' => 'mb-3'],
                'mapped' => false,
                'required' => false,
            ])
            ->add('seuil_alerte', null, [
                'attr' => ['class' => 'mb-3'],
            ])
            ->add('seuil_critique', null, [
                'attr' => ['class' => 'mb-3'],
            ])
            ->add('prix_public', MoneyType::class, $mb)
            ->add('prix_revendeur', MoneyType::class, $mb)
            /*->add('stock')*/
            ->add('dans_catalogue', null, [
                'required' => false,
                'attr' => ['class' => 'mb-3'],
            ])
            /*->add('collection')*/
            /*->add('taille')*/
            /*->add('utiliseMPs', CollectionType::class, [
                'entry_type' => UtiliseMPType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'label' => 'Matières premières',
                'attr' => ['class' => 'mb-3'],
            ])*/
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\CollectionArticle;
use App\Entity\Produit;
use App\Entity\StockProduit;
use App\Form\ProduitType;
use App\Form\SearchProduitType;
use App\Form\StockProduitType;
use App\Repository\ProduitRepository;
use App\Repository\StockProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Component\Pager\PaginatorInterface;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;
use App\Data\SearchProduit;

/**
 * @Route("/produit")
 */
class ProduitController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/", name="produit_index", methods={"GET"})
     */
    public function index(ProduitRepository $repository, Request $request): Response
    {
        if ($request->cookies->get('filter')) {
            $filter = SearchProduit::create($request->cookies->get('filter'));
            $filter->collections = $this->em->getRepository(CollectionArticle::class)->findBy(['id' => $filter->collections]);
            $filter->articles = $this->em->getRepository(Article::class)->findBy(['id' => $filter->articles]);
	    $filter->page = 1;
        } else $filter = new SearchProduit();


        if ($request->get('page')) {
            $filter->page = $request->get('page');
        }

        $form = $this->createForm(SearchProduitType::class, $filter);
        $form->handleRequest($request);

        $filter = $form->getData();

        if ($form->isSubmitted()) $filter->page = 1;

        $produits = $repository->findSearch($filter);

        $res = $this->render('produit/index.html.twig', [
            'produits' => $produits,
            'form' => $form->createView(),
        ]);
        $res->headers->setCookie(new Cookie('filter', $filter));

        return $res;
    }

    /**
     * @Route("/id<d+>", name="produit_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="produit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produit $produit): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produit_index');
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/stock", name="produit_stock_index", methods={"GET"})
     */
    public function stock(StockProduitRepository $repository, Produit $produit): Response
    {
        return $this->render('stock_produit/index.html.twig', [
            'stock_produits' => $repository->findBy(['produit' => $produit], ['date' => 'DESC']),
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/stock/update", name="produit_stock_update", methods={"GET","POST"})
     */
    public function updateStock(Request $request, Produit $produit): Response
    {
        $stockProduit = new StockProduit();
        $stockProduit
            ->setDate(new \DateTime())
            ->setProduit($produit)
            ->setOrigine("Modification manuelle");
        $form = $this->createForm(StockProduitType::class, $stockProduit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $stockProduit->appli();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_stock_index', ['id' => $produit->getId()]);
        }

        return $this->render('stock_produit/new.html.twig', [
            'stock' => $stockProduit,
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("{idProduit}/stock/{id}", name="produit_stock_delete", methods={"DELETE"})
     */
    public function deleteStock(Request $request, Produit $produit, StockProduit $stockProduit): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stockProduit->getId(), $request->request->get('_token'))) {
            // TODO: Géréer l'annulation d'une action du stock

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stockProduit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_stock_index');
    }

    /**
     * @Route("/exportProd", name="prod_excel", methods={"GET", "POST"})
     * @param ProduitRepository $produitRepository
     * @return Response
     */
  public function  excelgenpro(ProduitRepository $produitRepository) : Response
  {
      $spreadsheet = new Spreadsheet();
      $produits = $produitRepository->findAll(); //TODO : a changer selon la demande de caroline
      $sheet = $spreadsheet->getActiveSheet();


      $sheet->setCellValue("A1", "Référence Compta");
      $sheet->setCellValue("B1", "Taille");
      $sheet->setCellValue("C1", "Stock");
      $numofitem = 2;
      foreach ($produits as $item)
      {
          $cell = "A" . $numofitem;
          $vari = $item->getArticle()->getRefCompta();
          $sheet->setCellValue($cell, $vari);

          $cell = "B" . $numofitem;
          $vari = $item->getTaille();
          $sheet->setCellValue($cell, $vari);

          $cell = "C". $numofitem;
          $vari = $item->getStock();
          $sheet->setCellValue($cell, $vari);
          $numofitem = $numofitem + 1;
      }
      $writer = new Xlsx($spreadsheet);
      $ajd = mktime(0,0,0, date("m"), date("d"), date("Y"));
      $ajd = date("d.m.y");
      $fileName = 'StocksProduits_' . $ajd .".xlsx";
      $temp_file = tempnam(sys_get_temp_dir(), $fileName);
      $writer->save($temp_file);
      return $this->file($temp_file, $fileName, ResponseHeaderBag::DISPOSITION_INLINE);

  }

}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/_filter.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
<div class="m-2">
    {{ form_row(form.dans_catalogue) }}
</div>
{{ form_row(form.q) }}
<div class="mt-3">
    <h4>Collections</h4>
    {{ form_row(form.collections) }}
</div>
<div class="mt-3">
    <h4>Articles</h4>
    {{ form_row(form.articles) }}
</div>
<div class="row mt-3">
    <button type="submit" class="btn btn-primary col-9">Filtrer</button>
    <div class="col">
        {{ form_row(form.reset) }}
    </div>
</div>
{{ form_end(form) }}

templates/produit/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
{# <div class="row">
    <div class="col">{{ form_row(form.ref) }}</div>
    <div class="col">{{ form_row(form.refCompta) }}</div>
    <div class="col">{{ form_row(form.etiquette_marque) }}</div>
</div>
<div class="row">
    <div class="col">{{ form_row(form.prix_public) }}</div>
    <div class="col">{{ form_row(form.prix_revendeur) }}</div>
</div>
<div class="row">
    <div class="col">{{ form_row(form.seuil_alerte) }}</div>
    <div class="col">{{ form_row(form.seuil_critique) }}</div>
    <div class="col mt-4">{{ form_row(form.dans_catalogue) }}</div>
</div>
<div class="row">
    <div class="col mt-4">
        <button class="btn btn-primary">Enregistrer</button>
        <a href="{{ path('produit_index') }}" class="btn btn-secondary">Retour</a>
    </div>
    <div class="col">{{ form_row(form.utiliseMPs) }}</div>
</div> #}
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">{{ form_row(form.ref, {'label': 'Référence'}) }}</div>
            <div class="col">{{ form_row(form.refCompta) }}</div>
        </div>
        <div class="row">
            <div class="col">{{ form_row(form.prix_public, {'label': 'Prix Public (TTC)'}) }}  </div>
            <div class="col">{{ form_row(form.prix_revendeur , {'label': 'Prix Revendeur (HT)'}) }}</div>
        </div>
        <div class="row">
            <div class="col">{{ form_row(form.seuil_alerte) }}</div>
            <div class="col">{{ form_row(form.seuil_critique) }}</div>
        </div>
        <div class="row">
            <div class="col">
                <button class="btn btn-primary">Enregistrer</button>
                <a href="{{ path('produit_index') }}" class="btn btn-secondary">Retour</a>
                <a href="{{ path('produit_stock_index',{id: produit.id}) }}" class="btn btn-info">Modifier le stock</a>
            </div>
            <div class="col">
                {{ form_row(form.dans_catalogue) }}
            </div>
        </div>
    </div>
    {# <div class="col-5">{{ form_row(form.utiliseMPs) }}</div> #}
</div>
{{ form_end(form) }}

templates/produit/_form_theme.html.twig
{% block collection_row %}
    {% if prototype is defined %}
        {% set attr = attr|merge({'data-prototype': block('collection_item_widget') }) %}
    {% endif %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Fourniture</th>
            <th scope="col" class="col-2">Quantité / Long utile</th>
            <th scope="col" class="text-end">
                <a href="" class="mp-add" data-collection-holder-class="tags"><i class="bi bi-plus-circle fs-5"></i></a>
            </th>
        </tr>
        </thead>
        <tbody class="mp-warper" {{ block('widget_container_attributes') }}>
        {% for use in form %}
            <tr class="mp-item">
                <th scope="row">{{ form_widget(use.matiere_premiere) }}</th>
                <td>{{ form_widget(use.quantitee) }}</td>
                <td class="text-end">
                    <a href="" class="mp-remove"><i class="bi bi-x-circle fs-5 text-danger"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock collection_row %}

{% block collection_item_widget %}
    <tr class="col mp-item">
        <th scope="row">{{ form_widget(prototype.matiere_premiere) }}</th>
        <td>{{ form_widget(prototype.quantitee) }}</td>
        <td class="text-end">
            <a href="" class="mp-remove"><i class="bi bi-x-circle fs-5 text-danger"></i></a>
        </td>
    </tr>
{% endblock collection_item_widget %}

templates/produit/_pdf_theme.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <hr>
    <row>
        <columns>
            <p>
                Liste du stock de produit :
            </p>
        </columns>
    </row>
    <row>
        <columns>
            <table>
                <tr>
                    <th>#</th>
                    <th>Référence</th>
                    <th>Collection</th>
                    <th>Taille</th>
                    <th>Stock</th>
                    <th>Ref Compta</th>
                </tr>
                {% for produit in produits %}
                    <tr>
                        <td>{{ loop.index }}</td> {# permet d'afficher numero du for #}
                        <td>{{ produit.ref }}</td>
                        <td>{{ produit.collection }}</td>
                        <td>{{ produit.taille }}</td>
                        <td>{{ produit.stock }}</td>
                        <td>{{ produit.refCompta }}</td>
                    </tr>
                {% endfor %}
            </table>
        </columns>
    </row>
{% endblock %}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon catalogue{% endblock %}

{% block body %}
    <h1>Modifier mon produit : {{ produit.ref }}</h1>

    {{ include('produit/_form.html.twig') }}

{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Catalogue{% endblock %}

{% block body %}
    <h1>Catalogue</h1>
    <div class="text-end">

    </div>
    <div class="row">
        <div class="col-md-3">
            {% include 'produit/_filter.html.twig' with {form: form} only %}
            <div class="mt-3">
                <h4>Légende</h4>
                <table class="table">
                    <tbody>
                    <tr class="table-success">
                        <th>Stock > seuil d'alert</th>
                    </tr>
                    <tr class="table-warning">
                        <th>Stock < seuil d'alert</th>
                    </tr>
                    <tr class="table-danger">
                        <th>Stock < seuil critique</th>
                    </tr>
                    <tr class="table-secondary">
                        <th>Pas dans le catalogue</th>
                    </tr>
                    </tbody>
                </table>
                <td class="text-end">
                    <a href="{{ path('prod_excel') }}" class="btn btn-secondary">Stock produit</a>
                </td>
            </div>
        </div>
        <div class="col-md-9">

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">REF</th>
                    <th scope="col">{# {{ knp_pagination_sortable(produits, 'Collection', 'collection') }} #}
                        Collection
                    </th>
                    <th scope="col">{# {{ knp_pagination_sortable(produits, 'Article', 'article') }} #}Article</th>
                    <th scope="col">Taille</th>
                    <th scope="col">Stock</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for produit in produits %}
                    <tr class="align-middle table-{{ produit.etat }}">
                        <th scope="row">{{ produit.ref }}</th>
                        <td>{{ produit.collection }}</td>
                        <td>{{ produit.article }}</td>
                        <td>{{ produit.taille }}</td>
                        <td>
                            <a href="{{ path('produit_stock_index', {id: produit.id}) }}"
                               class="bi bi-arrow-down-up"></a>
                            {{ produit.stock }}
                        </td>
                        <td class="text-end">
                            {# TODO:Faire marcher ca : <a href="{{ path('produit_show', {id: produit.id}) }}" class="bi bi-eye fs-5"></a>#}
                            <a href="{{ path('article_taille_edit', {id: produit.taille.id, id_article: produit.article.id}) }}"
                               class="bi bi-list-check fs-5 {{ produit.taille.mpDef ? '' : 'text-danger' }}"></a>
                            <a href="{{ path('produit_edit', {id: produit.id}) }}"
                               class="bi bi-pencil-square fs-5"></a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">Aucun produit</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {{ knp_pagination_render(produits) }}
        </div>
    </div>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'un produit{% endblock %}

{% block body %}
    <h1>Créer un produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_index') }}">Retourner à la liste</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Collection</th>
                <td>{{ produit.collection }}</td>
            </tr>
            <tr>
                <th>Article</th>
                <td>{{ produit.taille.article }}</td>
            </tr>
            <tr>
                <th>Taille</th>
                <td>{{ produit.taille }}</td>
            </tr>
            <tr>
                <th>REF</th>
                <td>{{ produit.ref }}</td>
            </tr>
            <tr>
                <th>REF compta</th>
                <td>{{ produit.article.refCompta }}</td>
            </tr>
            <tr>
                <th>Seuil alerte</th>
                <td>{{ produit.seuilAlerte }}</td>
            </tr>
            <tr>
                <th>Seuil critique</th>
                <td>{{ produit.seuilCritique }}</td>
            </tr>
            <tr>
                <th>Prix public</th>
                <td>{{ produit.prixPublic }}</td>
            </tr>
            <tr>
                <th>Prix revendeur</th>
                <td>{{ produit.prixRevendeur }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ produit.stock }}</td>
            </tr>
            <tr>
                <th>Dans catalogue</th>
                <td>{{ produit.dansCatalogue ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th></th>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produit_edit', {'id': produit.id}) }}" class="btn btn-primary">Modifier</a>
    <a href="{{ path('produit_index') }}" class="btn btn-secondary">Retour</a>
{% endblock %}