src/Entity/CollectionArticle.php
<?php

namespace App\Entity;

use App\Repository\CollectionArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CollectionArticleRepository::class)
 * @UniqueEntity("nom")
 */
class CollectionArticle implements \JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\ManyToMany(targetEntity=Taille::class, cascade={"persist"})
     */
    private $tailles;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $motifFilename;

    /**
     * @ORM\ManyToOne(targetEntity=MatierePremiere::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $tissu;

    /**
     * @ORM\ManyToOne(targetEntity=MatierePremiere::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $couleur_noeud;

    public function __construct()
    {
        $this->tailles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return Collection|Taille[]
     */
    public function getTailles(): Collection
    {
        return $this->tailles;
    }

    public function addTaille(Taille $taille): self
    {
        if (!$this->tailles->contains($taille)) {
            $this->tailles[] = $taille;
        }

        return $this;
    }

    public function removeTaille(Taille $taille): self
    {
        $this->tailles->removeElement($taille);

        return $this;
    }

    public function getNbProduit(): int
    {
        return $this->tailles->count();
    }

    public function getMotifFilename(): ?string
    {
        return $this->motifFilename;
    }

    public function setMotifFilename(string $motifFilename): self
    {
        $this->motifFilename = $motifFilename;

        return $this;
    }

    public function getTissu(): ?MatierePremiere
    {
        return $this->tissu;
    }

    public function setTissu(?MatierePremiere $tissu): self
    {
        $this->tissu = $tissu;

        return $this;
    }

    public function getCouleurNoeud(): ?MatierePremiere
    {
        return $this->couleur_noeud;
    }

    public function setCouleurNoeud(?MatierePremiere $couleur_noeud): self
    {
        $this->couleur_noeud = $couleur_noeud;

        return $this;
    }

    public function __toString(): string {
        return $this->getNom();
    }

    public function jsonSerialize() {
        return $this->id;
    }
}

src/Form/CollectionArticleType.php
<?php

namespace App\Form;

use App\Entity\CollectionArticle;
use App\Entity\MatierePremiere;
use App\Entity\Taille;
use App\Form\Type\ArticlesType;
use App\Repository\MatierePremiereRepository;
use App\Repository\TailleRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class CollectionArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $mb = ['attr' => ['class' => 'mb-3']];
        $builder
            ->add('nom')
            ->add('commentaire')
            ->add('motifFile', FileType::class, [
                'mapped' => false,
                'constraints' => [new Image()],
                'label' => 'Motif',
                'attr' => [
                    'class' => 'form-control',
                    'onchange' => 'updateImage(this);'
                ],
                'required' => false,
            ])
            ->add('tissu', EntityType::class, [
                'class' => MatierePremiere::class,
                'attr' => ['required' => true],
                'query_builder' => function (MatierePremiereRepository $repository) {
                    return $repository->getQueryTissu();
                }
            ])
            ->add('couleurNoeud',EntityType::class, [
                'class' => MatierePremiere::class,
                'query_builder' => function (MatierePremiereRepository $repository) {
                    return $repository->getQueryNoeud();
                }
            ])
            ->add('addToCatalog', CheckboxType::class, [
                'mapped' => false,
                'label' => 'Ajouter au catalogue',
                'attr' => ['checked' => true],
                'required' => false,
            ])
            ->add('tailles', EntityType::class, [
                'class' => Taille::class,
                'multiple' => true,
                'expanded' => true,
                'choice_attr' => function ($choice, $key, $value) {
                    return ['class' => 'attending_' . strtolower($key)];
                },
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CollectionArticle::class,
        ]);
    }
}

src/Controller/CollectionArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\CollectionArticle;
use App\Entity\Produit;
use App\Form\CollectionArticleType;
use App\Repository\CollectionArticleRepository;
use App\Repository\MatierePremiereRepository;
use App\Service\UploaderHealper;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/collection")
 */
class CollectionArticleController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/", name="collection_index", methods={"GET"})
     */
    public function index(CollectionArticleRepository $repository): Response
    {
        return $this->render('collection_article/index.html.twig', [
            'collections' => $repository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="collection_new", methods={"GET","POST"})
     */
    public function new(Request $request, UploaderHealper $uploaderHealper): Response
    {
        $collection = new CollectionArticle();
        $form = $this->createForm(CollectionArticleType::class, $collection);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $uploadedFile = $form['motifFile']->getData();

            if ($uploadedFile) {
                $newFilename = $uploaderHealper->uploadMotifCollection($uploadedFile);
                $collection->setMotifFilename($newFilename);
            }

            $this->em->persist($collection);
            $this->em->flush();

            $this->addFlash('success', 'La collection a bien été créée');

            $dansCatalog = $form['addToCatalog']->getData();
            foreach ($collection->getTailles() as $taille) {
                $produit = new Produit();
                $produit
                    ->setCollection($collection)
                    ->setTaille($taille)
                    ->setDansCatalogue($dansCatalog)
                    ->setPrixPublic(0)
                    ->setPrixRevendeur(0)
                    ->setSeuilAlerte(20)
                    ->setSeuilCritique(10)
                    ->setRef(
                        substr($collection, 0, 3) .
                        substr($taille->getArticle(), 0, 3) .
                        $taille
                    );
                $this->em->persist($produit);
            }
            $this->em->flush();

            return $this->redirectToRoute('collection_index');
        }

        $articles = $this->getDoctrine()->getRepository(Article::class)->findAll();

        return $this->render('collection_article/new.html.twig', [
            'collection' => $collection,
            'articles' => $articles,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="collection_show", methods={"GET"})
     */
    public function show(CollectionArticle $collectionArticle): Response
    {
        return $this->render('collection_article/show.html.twig', [
            'collection_article' => $collectionArticle,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="collection_edit", methods={"GET","POST"})
     * @param Request $request
     * @param CollectionArticle $collection
     * @param $uploaderHealper
     * @return Response
     */
    public function edit(Request $request, CollectionArticle $collection, UploaderHealper $uploaderHealper): Response
    {
        $oldTaillesId = [];
        foreach ($collection->getTailles() as $taille) {
            $oldTaillesId[] = $taille->getId();
        }

        $form = $this->createForm(CollectionArticleType::class, $collection);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $uploadedFile = $form['motifFile']->getData();

            if ($uploadedFile) {
                $newFilename = $uploaderHealper->uploadMotifCollection($uploadedFile);
                $collection->setMotifFilename($newFilename);
            }

            $dansCatalog = $form['addToCatalog']->getData();
            foreach ($collection->getTailles() as $taille) {
                if (!in_array($taille->getId(), $oldTaillesId)) {
                    $produit = new Produit();
                    $produit
                        ->setCollection($collection)
                        ->setTaille($taille)
                        ->setDansCatalogue($dansCatalog)
                        ->setPrixPublic(0)
                        ->setPrixRevendeur(0)
                        ->setSeuilAlerte(20)
                        ->setSeuilCritique(10)
                        ->setRef(
                            substr($collection, 0, 3) .
                            substr($taille->getArticle(), 0, 3) .
                            substr($taille, 0, 3)
                        );
                    $this->em->persist($produit);
                }
            }
            $this->em->flush();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($collection);
            $entityManager->flush();

            return $this->redirectToRoute('collection_index');
        }

        $articles = $this->getDoctrine()->getRepository(Article::class)->findAll();

        return $this->render('collection_article/new.html.twig', [
            'collection' => $collection,
            'articles' => $articles,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="collection_delete", methods={"DELETE"})
     */
    public function delete(Request $request, CollectionArticle $collection): Response
    {
        if ($this->isCsrfTokenValid('delete' . $collection->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($collection);
            $entityManager->flush();
        }

        return $this->redirectToRoute('collection_index');
    }


}

templates/collection_article/_delete_form.html.twig
<form method="post" action="{{ path('collection_delete', {'id': collection.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette collection ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ collection.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/collection_article/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
<div class="row mb-3 my-5">
    <div class="col-8">
        <div class="row mb-3">
            <div class="col">{{ form_row(form.nom, {'label': 'Nom *'}) }}</div>
            <div class="col">{{ form_row(form.addToCatalog) }}</div>
        </div>
        {{ form_row(form.commentaire, {'row_attr': {'class':  'mb-3'}}) }}
        <div class="row mb-3">
            <div class="col">{{ form_row(form.tissu, {'label': 'Tissu *'}, {'row_attr': {'class':  'mb-3'}, 'required': modifReq}) }}</div>
            <div class="col">{{ form_row(form.couleurNoeud, {'label': 'Couleur noeud *'}) }}</div>
        </div>


        {# {{ form_row(form.tailles, {'attr': {'class': 'table'}}) }} #}
    </div>
    <div class="col-4 d-flex flex-column justify-content-between">
        {{ form_widget(form.motifFile, {'row_attr': {'class':  'mb-3'}}) }}
        <img id="imageMotif"
             src="{{ asset('uploads/collection_motif/')|default }}{{ collection.motifFilename|default }}"
             alt="{{ collection.nom|default }}" class="img-fluid">
    </div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col" class="w-25">
                Article *
                <a class="bi bi-check2-square" onclick="checkAll();"></a>
            </th>
            <th scope="col">Tailles</th>
        </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr class="align-middle">
                <th scope="row">{{ article.nom }}</th>
                <td>
                    {% for taille in article.tailles %}
                        {# TODO: Revoir style des badge (+ clickable sur tout le badge) #}
                        <div class="badge bg-secondary">
                            {{ form_widget(form.tailles[taille.id], {attr: {class: 'check-taille'}}) }}
                        </div>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="d-flex">
    <button class="btn btn-primary">Enregistrer</button>
    <a href="{{ path('collection_index') }}" class="btn">Retour</a>
</div>
{{ form_end(form) }}

templates/collection_article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une collection{% endblock %}

{% block body %}
    <h1>Modifier la collection : {{ collectionarticle.nom }}</h1>

    {% set modifReq = false %}
    {{ include('collection_article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('collection_index') }}">Retourner à la liste</a>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/collections/updateImage.js') }}"></script>
    <script src="{{ asset('js/collections/checkbox.js') }}"></script>
{% endblock %}

templates/collection_article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les collections{% endblock %}

{% block body %}
    <h1>Les Collections</h1>

    <table class="table table-striped mt-3">
        <thead>
        <tr class="align-middle">
            <th>Motif</th>
            <th>Nom</th>
            <th>Commentaire</th>
            <th>Nombre de produit</th>
            <th class="text-end">
                <a href="{{ path('collection_new') }}" class="btn btn-success">Créer une nouvelle collection</a>
            </th>
        </tr>
        </thead>
        <tbody>
        {% for collection in collections %}
            <tr class="align-middle">
                <td class="p-0">
                    <img src="{{ asset('uploads/collection_motif/') }}{{ collection.motifFilename }}"
                         alt="{{ collection.nom }}" style="height: 4em">
                </td>
                <th scope="row">{{ collection.nom }}</th>
                <td>{{ collection.commentaire }}</td>
                <td>{{ collection.nbProduit }}</td>
                <td>
                    <div class="d-flex justify-content-end">
                        <a href="{{ path('collection_edit', {'id': collection.id}) }}"
                           class="btn btn-primary me-1">Modifier</a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune collection</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/collection_article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <h1>Nouvelle collection</h1>

    {% set modifReq = true %}
    {{ include('collection_article/_form.html.twig') }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/collections/updateImage.js') }}"></script>
    <script src="{{ asset('js/collections/checkbox.js') }}"></script>
{% endblock %}

templates/collection_article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Collections{% endblock %}

{% block body %}
    <h1>Les Collections</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ collection_article.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ collection_article.nom }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ collection_article.commentaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('collection_index') }}">Retourner à la liste</a>

    <a href="{{ path('collection_edit', {'id': collection_article.id}) }}">Modifier</a>

{% endblock %}